
project_id = "vdtogebrtoqnbbpjntgg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_expiry = 10

[auth.email]
enable_confirmations = false

[auth.external.github]
enabled = true
client_id = "env(GITHUB_CLIENT_ID)"
secret = "env(GITHUB_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[experimental]
monitoring_enabled = true

[functions.openai-chat]
verify_jwt = true
import_map = "import_map.json"

[functions.memory-context]
verify_jwt = true
import_map = "import_map.json"

[functions.messages]
verify_jwt = true
import_map = "import_map.json"

[functions.reflect]
verify_jwt = true
import_map = "import_map.json"

[functions.flame-journal]
verify_jwt = true
import_map = "import_map.json"
