
project_id = "vdtogebrtoqnbbpjntgg"

[api]

[db]

[functions]

[functions.reflect]
verify_jwt = true

[functions.soulstate-evolution]
verify_jwt = true

[functions.intentions-synthesis]
verify_jwt = true
