
project_id = "vdtogebrtoqnbbpjntgg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = false

[studio]
enabled = false

[[function]]
name = "conversation-insights"
verify_jwt = true
