// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdtogebrtoqnbbpjntgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkdG9nZWJydG9xbmJicGpudGdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MzQyMjgsImV4cCI6MjA2MjMxMDIyOH0.NWY5_4Qx2q7D3zkwoHrnTt4018ophmFxf9WA0j4_5U4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);